cache:
  key: "$CI_BUILD_REF_NAME node:8-alpine"
  paths:
  - node_modules/
stages:
  - build
  - test
  - release
  - deploy
build:
  stage: build
  image: node:8-alpine
  variables:
    NODE_ENV: "development"
    script:
    - apk add --update bash
    - apk add --update git && rm -rf /tmp/* /var/cache/apk/*
    - npm install
test:
  stage: test
  image: node:8-alpine
  variables:
    NODE_ENV: "test"
  script:
    - npm run mocha
release:
  stage: release
  image: docker:latest
  only:
    - "master"
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: "overlay"
before_script:
    - docker version
    - "docker info"
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest --pull ."
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
  after_script:
    - "docker logout ${CI_REGISTRY}"
